name: zip-packaging

on: [ push, pull_request ]

jobs:
  create-zip-package:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/linuxcontainers/alpine:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Bun dependencies
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-
    
    - name: Install dependencies
      run: apk add blueprint-compiler typescript zip unzip make

    - uses: oven-sh/setup-bun@v2

    - name: Build & Package Noiseclapper
      run: make pack

    - name: Extract current branch name
      id: branch-name
      uses: tj-actions/branch-names@v7

    - name: Format branch name # Avoids GitHub Actions panicking about / characters in artifact names.
      id: format-branch-name
      run: echo "formatted_branch=$(echo ${{ steps.branch-name.outputs.current_branch }} | tr -s '/' '-')" >> $GITHUB_OUTPUT
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: noiseclapper-artifacts-${{ steps.format-branch-name.outputs.formatted_branch }}
        path: Noiseclapper@JordanViknar.zip