name: zip-generation

on: [ push, pull_request ]

jobs:
  generate-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Arch Linux
      run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh | su

    - name: Update Arch Linux
      run: pacman --noconfirm -Syyu

    - name: Install dependencies
      run: pacman --noconfirm -S blueprint-compiler make npm typescript 

    - name: Build & Package Noiseclapper
      run: make pack

    - name: Exit Arch Linux
      run: |
        exit
        exit

    - name: Extract current branch name
      id: branch-name
      uses: tj-actions/branch-names@v7
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: noiseclapper-artifacts-${{ steps.branch-name.outputs.current_branch }}
        path: Noiseclapper@JordanViknar.zip