name: zip-generation

on: [ push, pull_request ]

jobs:
  generate-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # This is where the download of the latest blueprint-compiler version would go... if Ubuntu had it.

    - name: Build & Package Noiseclapper
      run: make pack

    - name: Extract current branch name
      id: branch-name
      uses: tj-actions/branch-names@v7
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: noiseclapper-artifacts-${{ steps.branch-name.outputs.current_branch }}
        path: Noiseclapper@JordanViknar.zip