name: zip-generation

on: [ push, pull_request ]

jobs:
  generate-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Download blueprint-compiler from source
      run: git clone https://gitlab.gnome.org/jwestman/blueprint-compiler
    
    - name: Install dependencies
      run: sudo apt install -y gobject-introspection blueprint-compiler

    - name: Run blueprint-compiler manually
      run: mkdir dist && python3 ./blueprint-compiler/blueprint-compiler.py compile ui/prefs.blp > dist/prefs.ui

    - name: Build & Package Noiseclapper
      run: make pack

    - name: Extract current branch name
      id: branch-name
      uses: tj-actions/branch-names@v7
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: noiseclapper-artifacts-${{ steps.branch-name.outputs.current_branch }}
        path: Noiseclapper@JordanViknar.zip